output output/challenge_a2m_native_250/
load {
	saxs Datafiles/A2M_native.rsr
	pdb Datafiles/A2M_native.cif
	split chain
}
delete b5 b6 b7 b8 b9 b10 b11 b12 b13 b14
convert_to_symmetry {
	type d2
	bodies b1 b2 b3 b4
	tolerance 3
}
split b1 126 346 909 1249
autoconstrain backbone

save initial_state.pdb
save trajectory.xyz
parameter_generator {
	iterations 250
	translate 0.5
	rotate 0.02
	sym_translate 1
	sym_rotate 0.02
}
select random_constraint
transform rigid_transform

print "Initial chi2: {chi2_no_penalty}"
loop
	optimize_once
		on_improvement
			print {
				msg "{iteration}/{iterations_total}: Accepted with new chi2 {chi2_no_penalty}"
				colour green
			}
			update structure
			save trajectory.xyz
		end
	end
end
save final_state.pdb
