output output/rigidbody_pa2/
load {
	pdb Structures/PA2.CIF
	saxs Datafiles/PA2.dat
}
symmetry b1 p2

save initial_state.pdb
save trajectory.xyz
parameter_generator {
	iterations 100
	sym_translate 3
	sym_rotate 1.5
}
select random_body
transform single_transform

print "Initial chi2: {chi2_no_penalty}"
loop
	optimize_once
		on_improvement
			print {
				msg "{iteration}/{iterations_total}: Accepted with new chi2 {chi2_no_penalty}"
				colour green
			}
			update structure
			save trajectory.xyz
		end
	end
end
save final_state.pdb
