output output/pa2_from_gui_default/
load {
    pdb Datafiles/PA2.cif
    saxs Datafiles/PA2.dat
}
symmetry b1 p2
save initial_state.pdb
save trajectory.xyz
parameter_generator {
    iterations 500
    sym_translate 20
    sym_rotate 1.5
}

print "Initial chi2: {chi2_no_penalty}"
loop
    optimize_once
        on_improvement
            print {
                msg "{iteration}/{iterations_total}: Accepted with new chi2 {chi2_no_penalty}"
                colour green
            }
            update structure
            save trajectory.xyz
        end
    end
end
save final_state.pdb
